// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/genefriendway/onchain-handler/conf"
	interfaces2 "github.com/genefriendway/onchain-handler/infra/interfaces"
	"github.com/genefriendway/onchain-handler/internal/adapters/repositories"
	"github.com/genefriendway/onchain-handler/internal/interfaces"
	"github.com/genefriendway/onchain-handler/internal/ucases"
	interfaces3 "github.com/genefriendway/onchain-handler/pkg/interfaces"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// Init ucase
func InitializeBlockStateUCase(db *gorm.DB) interfaces.BlockStateUCase {
	blockStateRepository := repositories.NewBlockstateRepository(db)
	blockStateUCase := ucases.NewBlockStateUCase(blockStateRepository)
	return blockStateUCase
}

func InitializePaymentOrderUCase(db *gorm.DB, cacheRepo interfaces2.CacheRepository, config *conf.Configuration) interfaces.PaymentOrderUCase {
	paymentOrderRepository := repositories.NewPaymentOrderRepository(db)
	interfacesPaymentOrderRepository := repositories.NewPaymentOrderCacheRepository(paymentOrderRepository, cacheRepo, config)
	paymentWalletRepository := repositories.NewPaymentWalletRepository(db, config)
	blockStateRepository := repositories.NewBlockstateRepository(db)
	paymentOrderUCase := ucases.NewPaymentOrderUCase(db, interfacesPaymentOrderRepository, paymentWalletRepository, blockStateRepository, cacheRepo, config)
	return paymentOrderUCase
}

func InitializeTokenTransferUCase(db *gorm.DB, ethClient interfaces3.Client, config *conf.Configuration) interfaces.TokenTransferUCase {
	tokenTransferRepository := repositories.NewTokenTransferRepository(db)
	tokenTransferUCase := ucases.NewTokenTransferUCase(tokenTransferRepository, ethClient, config)
	return tokenTransferUCase
}

func InitializePaymentEventHistoryUCase(db *gorm.DB, cacheRepo interfaces2.CacheRepository, config *conf.Configuration) interfaces.PaymentEventHistoryUCase {
	paymentEventHistoryRepository := repositories.NewPaymentEventHistoryRepository(db)
	interfacesPaymentEventHistoryRepository := repositories.NewPaymentEventHistoryCacheRepository(paymentEventHistoryRepository, cacheRepo, config)
	paymentEventHistoryUCase := ucases.NewPaymentEventHistoryUCase(interfacesPaymentEventHistoryRepository)
	return paymentEventHistoryUCase
}

func InitializePaymentWalletUCase(db *gorm.DB, config *conf.Configuration) interfaces.PaymentWalletUCase {
	paymentWalletRepository := repositories.NewPaymentWalletRepository(db, config)
	paymentWalletBalanceRepository := repositories.NewPaymentWalletBalanceRepository(db)
	paymentWalletUCase := ucases.NewPaymentWalletUCase(db, paymentWalletRepository, paymentWalletBalanceRepository)
	return paymentWalletUCase
}

func InitializeUserWalletUCase(db *gorm.DB, config *conf.Configuration) interfaces.UserWalletUCase {
	userWalletRepository := repositories.NewUserWalletRepository(db)
	userWalletUCase := ucases.NewUserWalletUCase(userWalletRepository)
	return userWalletUCase
}

func InitializeNetworkMetadataUCase(db *gorm.DB, cacheRepo interfaces2.CacheRepository) interfaces.NetworkMetadataUCase {
	networkMetadataRepository := repositories.NewNetworkMetadataRepository(db)
	interfacesNetworkMetadataRepository := repositories.NewNetworkMetadataCacheRepository(networkMetadataRepository, cacheRepo)
	networkMetadataUCase := ucases.NewNetworkMetadataUCase(interfacesNetworkMetadataRepository)
	return networkMetadataUCase
}

// wire.go:

// UCase set
var blockStateUCaseSet = wire.NewSet(repositories.NewBlockstateRepository, ucases.NewBlockStateUCase)

var paymentOrderUCaseSet = wire.NewSet(repositories.NewPaymentOrderRepository, repositories.NewPaymentOrderCacheRepository, repositories.NewPaymentWalletRepository, repositories.NewBlockstateRepository, ucases.NewPaymentOrderUCase)

var tokenTransferUCaseSet = wire.NewSet(repositories.NewTokenTransferRepository, ucases.NewTokenTransferUCase)

var paymentEventHistoryUCaseSet = wire.NewSet(repositories.NewPaymentEventHistoryRepository, repositories.NewPaymentEventHistoryCacheRepository, ucases.NewPaymentEventHistoryUCase)

var paymentWalletUCaseSet = wire.NewSet(repositories.NewPaymentWalletRepository, repositories.NewPaymentWalletBalanceRepository, ucases.NewPaymentWalletUCase)

var userWalletUCaseSet = wire.NewSet(repositories.NewUserWalletRepository, ucases.NewUserWalletUCase)

var networkMetadataUCaseSet = wire.NewSet(repositories.NewNetworkMetadataRepository, repositories.NewNetworkMetadataCacheRepository, ucases.NewNetworkMetadataUCase)
