// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/interfaces/logger.go
//
// Generated by this command:
//
//	mockgen -source=pkg/interfaces/logger.go -destination=pkg/mocks/mock_logger.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	interfaces "github.com/genefriendway/onchain-handler/pkg/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", message)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), message)
}

// Debugf mocks base method.
func (m *MockLogger) Debugf(format string, values ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerMockRecorder) Debugf(format any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", message)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), message)
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(format string, values ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(format any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// Fatal mocks base method.
func (m *MockLogger) Fatal(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatal", message)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerMockRecorder) Fatal(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), message)
}

// Fatalf mocks base method.
func (m *MockLogger) Fatalf(format string, values ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockLoggerMockRecorder) Fatalf(format any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockLogger)(nil).Fatalf), varargs...)
}

// GetConfig mocks base method.
func (m *MockLogger) GetConfig() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockLoggerMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockLogger)(nil).GetConfig))
}

// GetLogLevel mocks base method.
func (m *MockLogger) GetLogLevel() interfaces.Level {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogLevel")
	ret0, _ := ret[0].(interfaces.Level)
	return ret0
}

// GetLogLevel indicates an expected call of GetLogLevel.
func (mr *MockLoggerMockRecorder) GetLogLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogLevel", reflect.TypeOf((*MockLogger)(nil).GetLogLevel))
}

// GetServiceName mocks base method.
func (m *MockLogger) GetServiceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServiceName indicates an expected call of GetServiceName.
func (mr *MockLoggerMockRecorder) GetServiceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceName", reflect.TypeOf((*MockLogger)(nil).GetServiceName))
}

// Info mocks base method.
func (m *MockLogger) Info(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", message)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), message)
}

// Infof mocks base method.
func (m *MockLogger) Infof(format string, values ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(format any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// Panic mocks base method.
func (m *MockLogger) Panic(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Panic", message)
}

// Panic indicates an expected call of Panic.
func (mr *MockLoggerMockRecorder) Panic(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panic", reflect.TypeOf((*MockLogger)(nil).Panic), message)
}

// Panicf mocks base method.
func (m *MockLogger) Panicf(format string, values ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Panicf", varargs...)
}

// Panicf indicates an expected call of Panicf.
func (mr *MockLoggerMockRecorder) Panicf(format any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panicf", reflect.TypeOf((*MockLogger)(nil).Panicf), varargs...)
}

// SetConfig mocks base method.
func (m *MockLogger) SetConfig(config any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfig", config)
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockLoggerMockRecorder) SetConfig(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockLogger)(nil).SetConfig), config)
}

// SetConfigModeByCode mocks base method.
func (m *MockLogger) SetConfigModeByCode(code string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfigModeByCode", code)
}

// SetConfigModeByCode indicates an expected call of SetConfigModeByCode.
func (mr *MockLoggerMockRecorder) SetConfigModeByCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigModeByCode", reflect.TypeOf((*MockLogger)(nil).SetConfigModeByCode), code)
}

// SetLogLevel mocks base method.
func (m *MockLogger) SetLogLevel(level interfaces.Level) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogLevel", level)
}

// SetLogLevel indicates an expected call of SetLogLevel.
func (mr *MockLoggerMockRecorder) SetLogLevel(level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogLevel", reflect.TypeOf((*MockLogger)(nil).SetLogLevel), level)
}

// SetServiceName mocks base method.
func (m *MockLogger) SetServiceName(serviceName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetServiceName", serviceName)
}

// SetServiceName indicates an expected call of SetServiceName.
func (mr *MockLoggerMockRecorder) SetServiceName(serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetServiceName", reflect.TypeOf((*MockLogger)(nil).SetServiceName), serviceName)
}

// Warn mocks base method.
func (m *MockLogger) Warn(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", message)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), message)
}

// Warnf mocks base method.
func (m *MockLogger) Warnf(format string, values ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerMockRecorder) Warnf(format any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}

// WithFields mocks base method.
func (m *MockLogger) WithFields(fields map[string]any) interfaces.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithFields", fields)
	ret0, _ := ret[0].(interfaces.Logger)
	return ret0
}

// WithFields indicates an expected call of WithFields.
func (mr *MockLoggerMockRecorder) WithFields(fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithFields", reflect.TypeOf((*MockLogger)(nil).WithFields), fields)
}

// WithInterface mocks base method.
func (m *MockLogger) WithInterface(key string, value any) interfaces.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithInterface", key, value)
	ret0, _ := ret[0].(interfaces.Logger)
	return ret0
}

// WithInterface indicates an expected call of WithInterface.
func (mr *MockLoggerMockRecorder) WithInterface(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithInterface", reflect.TypeOf((*MockLogger)(nil).WithInterface), key, value)
}

// MockLoggerFactory is a mock of LoggerFactory interface.
type MockLoggerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerFactoryMockRecorder
	isgomock struct{}
}

// MockLoggerFactoryMockRecorder is the mock recorder for MockLoggerFactory.
type MockLoggerFactoryMockRecorder struct {
	mock *MockLoggerFactory
}

// NewMockLoggerFactory creates a new mock instance.
func NewMockLoggerFactory(ctrl *gomock.Controller) *MockLoggerFactory {
	mock := &MockLoggerFactory{ctrl: ctrl}
	mock.recorder = &MockLoggerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerFactory) EXPECT() *MockLoggerFactoryMockRecorder {
	return m.recorder
}

// CreateLogger mocks base method.
func (m *MockLoggerFactory) CreateLogger(config any) (interfaces.Logger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLogger", config)
	ret0, _ := ret[0].(interfaces.Logger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLogger indicates an expected call of CreateLogger.
func (mr *MockLoggerFactoryMockRecorder) CreateLogger(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogger", reflect.TypeOf((*MockLoggerFactory)(nil).CreateLogger), config)
}
