ARG IMAGE_REPOSITORY=741499881865.dkr.ecr.ap-southeast-1.amazonaws.com/life-ai/life-point-onchain-handler
ARG IMAGE_TAG=latest

FROM ${IMAGE_REPOSITORY}:${IMAGE_TAG}

LABEL maintainer="Duong <duong@genetica.asia>"
