version: '3.8'

services:
  app:
    build:
      context: .  # Path to Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: onchain-handler

      BSC_RPC_URL: https://bsc-testnet-rpc.publicnode.com
      BSC_CHAIN_ID: 97
      BSC_START_BLOCK_LISTENER: 45843000
      BSC_USDT_CONTRACT_ADDRESS: 0xc4E680309AE00BF8a517428335C846B75b9b0390

      AVAX_RPC_URL: https://api.avax-test.network/ext/bc/C/rpc
      AVAX_CHAIN_ID: 43113
      AVAX_START_BLOCK_LISTENER: 36785000
      AVAX_USDT_CONTRACT_ADDRESS: 0xa18523a7f8Be602df294a7804a510381fbE1760a
      AVAX_LIFE_POINT_CONTRACT_ADDRESS: 0x50B7C0d6A27149181abd17c3F427084C800f178c
      AVAX_BULK_SENDER_CONTRACT_ADDRESS: 0xf3c16A130aC33E9b3f0A786c5705a15830E12186

      LP_TREASURY_ADDRESS: 0x326ee3fbD294aCa6f33C60847A80883Ce25A92AD
      USDT_TREASURY_ADDRESS: 0xB9F2fa90DBB47cd08e43aFA1b4D2C2620D80d193
      LP_COMMUNITY_ADDRESS: 0x7395b6C80f32A1F410b8B0591143a164bf7117b9
      LP_REVENUE_ADDRESS: 0x8EDBFc7Dcda975c7e23a48FF143878574E854E97
      LP_STAKING_ADDRESS: 0x1e854bbd9d17E002024234D172BF7fB229ad9774

      INIT_WALLET_COUNT: 10
      EXPIRED_ORDER_TIME: 15
      PAYMENT_COVERING: 1.2

      PRIVATE_KEY_LP_TREASURY: ${PRIVATE_KEY_LP_TREASURY}
      PRIVATE_KEY_USDT_TREASURY: ${PRIVATE_KEY_USDT_TREASURY}
      PRIVATE_KEY_LP_COMMUNITY: ${PRIVATE_KEY_LP_COMMUNITY}
      PRIVATE_KEY_LP_REVENUE: ${PRIVATE_KEY_LP_REVENUE}
      PRIVATE_KEY_LP_STAKING: ${PRIVATE_KEY_LP_STAKING}
      MNEMONIC: ${MNEMONIC}
      PASSPHRASE: ${PASSPHRASE}
      SALT: ${SALT}
    depends_on:
      db:
        condition: service_healthy  # Wait for the db service to become healthy
    networks:
      - onchain-handler-network

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: onchain-handler
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d  # Mount SQL scripts to initdb.d directory
    ports:
      - "5432:5432"
    networks:
      - onchain-handler-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  onchain-handler-network:
