definitions:
  dto.MembershipEventDTO:
    properties:
      amount:
        type: string
      end_duration:
        type: string
      id:
        type: integer
      order_id:
        type: integer
      status:
        type: integer
      transaction_hash:
        type: string
      user_address:
        type: string
    type: object
  dto.TransferTokenPayloadDTO:
    properties:
      recipient_address:
        type: string
      token_amount:
        type: string
      tx_type:
        type: string
    type: object
  util.GeneralError:
    properties:
      code:
        description: HTTP error code, or custom error code
        type: integer
      errors:
        description: List of error send server 2 server
        items:
          type: string
        type: array
      string:
        description: Friendly error message
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/membership/events:
    get:
      consumes:
      - application/json
      description: This endpoint fetches a list of membership events based on the
        provided comma-separated list of order IDs.
      parameters:
      - description: Comma-separated list of order IDs
        in: query
        name: orderIds
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful retrieval of membership events
          schema:
            items:
              $ref: '#/definitions/dto.MembershipEventDTO'
            type: array
        "400":
          description: Invalid Order IDs or missing Order IDs
          schema:
            $ref: '#/definitions/util.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Retrieve membership events by order IDs
      tags:
      - membership
  /api/v1/transfer:
    post:
      consumes:
      - application/json
      description: This endpoint allows the distribution of tokens to multiple recipients.
        It accepts a list of transfer requests, validates the payload, and processes
        the token transfers based on the transaction type.
      parameters:
      - description: List of transfer requests. Each request must include recipient
          address and transaction type.
        in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.TransferTokenPayloadDTO'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 'Success response: {\"success\": true}'
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: Invalid payload or invalid recipient address/transaction type
          schema:
            $ref: '#/definitions/util.GeneralError'
        "500":
          description: Internal server error, failed to distribute tokens
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Distribute tokens to recipients
      tags:
      - transfer
swagger: "2.0"
