definitions:
  dto.TokenTransferHistoryDTO:
    properties:
      error_message:
        type: string
      fee:
        type: string
      from_address:
        type: string
      id:
        type: integer
      request_id:
        type: string
      status:
        type: boolean
      symbol:
        type: string
      to_address:
        type: string
      token_amount:
        type: string
      transaction_hash:
        type: string
    type: object
  dto.TokenTransferHistoryDTOResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.TokenTransferHistoryDTO'
        type: array
      next_page:
        type: integer
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
    type: object
  dto.TokenTransferPayloadDTO:
    properties:
      from_address:
        type: string
      request_id:
        type: string
      symbol:
        type: string
      to_address:
        type: string
      token_amount:
        type: string
    type: object
  util.GeneralError:
    properties:
      code:
        description: HTTP error code, or custom error code
        type: integer
      errors:
        description: List of error send server 2 server
        items:
          type: string
        type: array
      string:
        description: Friendly error message
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/token-transfer:
    post:
      consumes:
      - application/json
      description: This endpoint allows the distribution of tokens to multiple recipients.
        It accepts a list of transfer requests, validates the payload, and processes
        the token transfers based on the transaction type.
      parameters:
      - description: List of transfer requests. Each request must include recipient
          address and transaction type.
        in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.TokenTransferPayloadDTO'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 'Success response: {\"success\": true}'
          schema:
            additionalProperties:
              type: boolean
            type: object
        "400":
          description: Invalid payload or invalid recipient address/transaction type
          schema:
            $ref: '#/definitions/util.GeneralError'
        "500":
          description: Internal server error, failed to distribute tokens
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Distribute tokens to recipients
      tags:
      - token-transfer
  /api/v1/token-transfer/histories:
    get:
      consumes:
      - application/json
      description: This endpoint fetches a paginated list of token transfer histories
        filtered by request IDs and time range.
      parameters:
      - description: Page number, default is 1
        in: query
        name: page
        type: integer
      - description: Page size, default is 10
        in: query
        name: size
        type: integer
      - collectionFormat: csv
        description: List of request IDs to filter
        in: query
        items:
          type: string
        name: request_ids
        type: array
      - description: Start time in RFC3339 format to filter example(
        example: '"2024-01-01T00:00:00Z"'
        in: query
        name: start_time
        type: string
      - description: End time in RFC3339 format to filter example(
        example: '"2024-02-01T00:00:00Z"'
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful retrieval of token transfer histories
          schema:
            $ref: '#/definitions/dto.TokenTransferHistoryDTOResponse'
        "400":
          description: Invalid parameters
          schema:
            $ref: '#/definitions/util.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/util.GeneralError'
      security:
      - ApiKeyAuth: []
      summary: Get list of token transfer histories
      tags:
      - token-transfer
swagger: "2.0"
